### ISSUE TITLE
Navbar, Section: Header.js

### ISSUE THREAD

**Issue by OkApollo** [OkAbstract/Website370#1]
<img width="727" alt="Screen Shot 2022-08-21 at 2 34 08 PM" src="https://user-images.githubusercontent.com/72602829/185786928-2aa1a9aa-7fd5-4fea-8b69-388bf951b545.png">

**Comment by OkApollo** [comment]
Yo so make a icon too so make sure to import some icons from react bootstrap and you'll be done with the nav bar :) ok bye future me :)

**Comment by ignatiusobiorah** [comment]
can you explain better please.. I don't understand

**Comment by OkApollo** [comment]
> can you explain better please.. I don't understand

Ah hello, I am basically making a Navigation bar as a starter for my website with React.Js. So what I am planning is making a custom Navigation Bar.

**Comment by irfen-mi** [comment]
hey @AbstractBeats assign me this i will create responsive navbar.

**Comment by OkApollo** [comment]
> hey @AbstractBeats assign me this i will create responsive navbar.

I've made this for reminders and letting me know what to add and stuff. Therefore no thank you, I am good.

**Comment by OkApollo** [comment]
Navbar completed :)
